const longbounce3v3 = `{

  "name" : "Longbounce 3v3 by El Bicho",

  "width" : 9600,

  "height" : 280,

  "spawnDistance" : 350,

  "bg" : { "type" : "hockey", "width" : 9600, "height" : 192, "kickOffRadius" : 20, "cornerRadius" : 0 },

  "vertexes" : [
    /* 0 */ { "x" : -9493, "y" : 184, "trait" : "ballArea" },
    /* 1 */ { "x" : -9492, "y" : 192, "trait" : "ballArea", "curve" : 23, "color" : "e9cc6e", "cMask" : ["wall" ] },
    /* 2 */ { "x" : -9493, "y" : -192, "trait" : "ballArea", "color" : "e9cc6e", "cMask" : ["wall" ], "curve" : 23 },
    /* 3 */ { "x" : -9492, "y" : -182, "trait" : "ballArea" },
    /* 4 */ { "x" : 9500, "y" : 222, "trait" : "ballArea" },
    /* 5 */ { "x" : 9500, "y" : 192, "trait" : "ballArea", "color" : "e9cc6e", "curve" : 22, "cMask" : ["wall" ] },
    /* 6 */ { "x" : 9500, "y" : -192, "trait" : "ballArea", "color" : "e9cc6e", "curve" : 22, "cMask" : ["wall" ] },
    /* 7 */ { "x" : 9500, "y" : -218, "trait" : "ballArea" },
    
    /* 8 */ { "x" : 0, "y" : 280, "trait" : "kickOffBarrier" },
    /* 9 */ { "x" : 0, "y" : 20, "trait" : "kickOffBarrier", "color" : "b34e4e" },
    /* 10 */ { "x" : 0, "y" : -20, "trait" : "kickOffBarrier", "color" : "b34e4e" },
    /* 11 */ { "x" : 0, "y" : -280, "trait" : "kickOffBarrier" },
    
    /* 12 */ { "x" : -8727, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 13 */ { "x" : -8727, "y" : -171, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 14 */ { "x" : 872, "y" : 150, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 15 */ { "x" : 872, "y" : 190, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 16 */ { "x" : -1745, "y" : 169, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 17 */ { "x" : -1745, "y" : 189, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    
    /* 18 */ { "x" : -872, "y" : 151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "trait" : "ballArea" },
    /* 19 */ { "x" : -872, "y" : 191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "trait" : "ballArea" },
    
    /* 20 */ { "x" : -4363, "y" : 150, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 21 */ { "x" : -4363, "y" : 190, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 22 */ { "x" : -5236, "y" : 171, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 23 */ { "x" : -5236, "y" : 191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 24 */ { "x" : -6109, "y" : 150, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 25 */ { "x" : -6109, "y" : 190, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 26 */ { "x" : -6981, "y" : 170, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 27 */ { "x" : -6981, "y" : 190, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 28 */ { "x" : -7854, "y" : 148, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 29 */ { "x" : -7854, "y" : 188, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 30 */ { "x" : -8727, "y" : 167, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 31 */ { "x" : -8727, "y" : 191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 32 */ { "x" : -3490, "y" : 169, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 33 */ { "x" : -3490, "y" : 189, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 34 */ { "x" : -2618, "y" : 151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 35 */ { "x" : -2618, "y" : 191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 36 */ { "x" : 1745, "y" : 171, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 37 */ { "x" : 1745, "y" : 191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 38 */ { "x" : 2618, "y" : 151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 39 */ { "x" : 2618, "y" : 191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 40 */ { "x" : 3490, "y" : 170, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 41 */ { "x" : 3490, "y" : 190, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 42 */ { "x" : 4363, "y" : 151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 43 */ { "x" : 4363, "y" : 191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 44 */ { "x" : 5236, "y" : 171, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 45 */ { "x" : 5236, "y" : 191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 46 */ { "x" : 6109, "y" : 150, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 47 */ { "x" : 6109, "y" : 190, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 48 */ { "x" : 6981, "y" : 172, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 49 */ { "x" : 6981, "y" : 192, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 50 */ { "x" : 7854, "y" : 150, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 51 */ { "x" : 7854, "y" : 190, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 52 */ { "x" : 8727, "y" : 172, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 53 */ { "x" : 8727, "y" : 192, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 54 */ { "x" : -7854, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 55 */ { "x" : -7854, "y" : -151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 56 */ { "x" : -6981, "y" : -192, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 57 */ { "x" : -6981, "y" : -172, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 58 */ { "x" : -6109, "y" : -192, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 59 */ { "x" : -6109, "y" : -152, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 60 */ { "x" : -5236, "y" : -192, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 61 */ { "x" : -5236, "y" : -172, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 62 */ { "x" : -4363, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 63 */ { "x" : -4363, "y" : -151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 64 */ { "x" : -3490, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 65 */ { "x" : -3490, "y" : -171, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 66 */ { "x" : -2618, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 67 */ { "x" : -2618, "y" : -151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 68 */ { "x" : -1745, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 69 */ { "x" : -1745, "y" : -171, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 70 */ { "x" : -872, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 71 */ { "x" : -872, "y" : -151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 72 */ { "x" : 872, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 73 */ { "x" : 872, "y" : -151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 74 */ { "x" : 1745, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 75 */ { "x" : 1745, "y" : -171, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 76 */ { "x" : 2618, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 77 */ { "x" : 2618, "y" : -151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 78 */ { "x" : 3490, "y" : -192, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 79 */ { "x" : 3490, "y" : -172, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 80 */ { "x" : 4363, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 81 */ { "x" : 4363, "y" : -151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 82 */ { "x" : 5236, "y" : -192, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 83 */ { "x" : 5236, "y" : -172, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 84 */ { "x" : 6109, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 85 */ { "x" : 6109, "y" : -151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 86 */ { "x" : 6981, "y" : -192, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 87 */ { "x" : 6981, "y" : -172, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 88 */ { "x" : 7854, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 89 */ { "x" : 7854, "y" : -151, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 90 */ { "x" : 8727, "y" : -191, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    /* 91 */ { "x" : 8727, "y" : -171, "color" : "e9cc6e", "cMask" : ["wall" ], "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true },
    
    /* 92 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 7825, "y" : 219, "curve" : 0 },
    /* 93 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 7837, "y" : 207, "curve" : 0 },
    /* 94 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 7837, "y" : 236, "curve" : 0 },
    
    /* 95 */ { "cMask" : ["ball" ], "x" : 6081, "y" : 210, "cGroup" : ["ball","red","blue" ] },
    /* 96 */ { "cMask" : ["ball" ], "x" : 6103, "y" : 209, "curve" : 28.7683142519, "cGroup" : ["ball","red","blue" ] },
    /* 97 */ { "cMask" : ["ball" ], "x" : 6082, "y" : 223, "curve" : 28.7683142519, "cGroup" : ["ball","red","blue" ] },
    /* 98 */ { "cMask" : ["ball" ], "x" : 6103, "y" : 224, "cGroup" : ["ball","red","blue" ] },
    
    /* 99 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 4337, "y" : 205 },
    /* 100 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 4356, "y" : 205 },
    /* 101 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 4345, "y" : 218 },
    /* 102 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 4337, "y" : 235 },
    /* 103 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 2617, "y" : 226 },
    /* 104 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 2594, "y" : 226 },
    /* 105 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 2613, "y" : 206 },
    /* 106 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 2611, "y" : 235 },
    /* 107 */ { "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 2611, "y" : 216 },
    /* 108 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 866, "y" : 203 },
    /* 109 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 849, "y" : 203 },
    /* 110 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 850, "y" : 218, "curve" : 250 },
    /* 111 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -877, "y" : 204 },
    /* 112 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -893, "y" : 204 },
    /* 113 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 849, "y" : 217, "curve" : 250 },
    /* 114 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 849, "y" : 232, "curve" : 250 },
    /* 115 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -893, "y" : 204 },
    /* 116 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -893, "y" : 204 },
    /* 117 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -893, "y" : 218, "curve" : 250 },
    /* 118 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -893, "y" : 204 },
    /* 119 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -893, "y" : 204 },
    /* 120 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -893, "y" : 218, "curve" : 250 },
    /* 121 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -893, "y" : 233, "curve" : 250 },
    /* 122 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -2625, "y" : 220 },
    /* 123 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -2648, "y" : 220 },
    /* 124 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -2631, "y" : 201 },
    /* 125 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -2631, "y" : 230 },
    /* 126 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -2631, "y" : 213 },
    /* 127 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -4388, "y" : 202 },
    /* 128 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -4369, "y" : 202 },
    /* 129 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -4380, "y" : 214 },
    /* 130 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -4388, "y" : 231 },
    
    /* 131 */ { "cMask" : ["ball" ], "x" : -6134, "y" : 206, "cGroup" : ["ball","red","blue" ], "bCoef" : 0 },
    /* 132 */ { "cMask" : ["ball" ], "x" : -6118, "y" : 211, "curve" : 28.7683142519, "cGroup" : ["ball","red","blue" ], "bCoef" : 0 },
    /* 133 */ { "cMask" : ["ball" ], "x" : -6134, "y" : 229, "curve" : 28.7683142519, "cGroup" : ["ball","red","blue" ], "bCoef" : 0 },
    /* 134 */ { "cMask" : ["ball" ], "x" : -6118, "y" : 229, "cGroup" : ["ball","red","blue" ], "bCoef" : 0 },
    
    /* 135 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -7870, "y" : 213 },
    /* 136 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -7864, "y" : 200 },
    /* 137 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -7864, "y" : 229 },
    /* 138 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 7868, "y" : 212, "curve" : -180, "color" : "e9cc6e" },
    /* 139 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 7868, "y" : 232, "curve" : -180, "color" : "e9cc6e" },
    /* 140 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 6123, "y" : 204, "curve" : -180, "color" : "e9cc6e" },
    /* 141 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 6123, "y" : 224, "curve" : -180, "color" : "e9cc6e" },
    /* 142 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 4377, "y" : 210, "curve" : -180, "color" : "e9cc6e" },
    /* 143 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 4377, "y" : 230, "curve" : -180, "color" : "e9cc6e" },
    /* 144 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 2632, "y" : 211, "curve" : -180, "color" : "e9cc6e" },
    /* 145 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 2632, "y" : 231, "curve" : -180, "color" : "e9cc6e" },
    /* 146 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 886, "y" : 208, "curve" : -180, "color" : "e9cc6e" },
    /* 147 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : 886, "y" : 228, "curve" : -180, "color" : "e9cc6e" },
    /* 148 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -858, "y" : 209, "curve" : -180, "color" : "e9cc6e" },
    /* 149 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -858, "y" : 229, "curve" : -180, "color" : "e9cc6e" },
    /* 150 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -2605, "y" : 206, "curve" : -180, "color" : "e9cc6e" },
    /* 151 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -2605, "y" : 226, "curve" : -180, "color" : "e9cc6e" },
    /* 152 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -4349, "y" : 207, "curve" : -180, "color" : "e9cc6e" },
    /* 153 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -4349, "y" : 227, "curve" : -180, "color" : "e9cc6e" },
    /* 154 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -6094, "y" : 205, "curve" : -180, "color" : "e9cc6e" },
    /* 155 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -6094, "y" : 225, "curve" : -180, "color" : "e9cc6e" },
    /* 156 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -7841, "y" : 205, "curve" : -180, "color" : "e9cc6e" },
    /* 157 */ { "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "x" : -7841, "y" : 225, "curve" : -180, "color" : "e9cc6e" }

  ],

  "segments" : [
    { "v0" : 0, "v1" : 1, "trait" : "ballArea" },
    { "v0" : 2, "v1" : 3, "trait" : "ballArea" },
    { "v0" : 4, "v1" : 5, "trait" : "ballArea" },
    { "v0" : 6, "v1" : 7, "trait" : "ballArea" },
    
    { "v0" : 8, "v1" : 9, "trait" : "kickOffBarrier" },
    { "v0" : 9, "v1" : 10, "trait" : "kickOffBarrier", "curve" : 180, "cGroup" : ["blueKO" ], "color" : "b34e4e" },
    { "v0" : 9, "v1" : 10, "trait" : "kickOffBarrier", "curve" : -180, "cGroup" : ["redKO" ], "color" : "5e5eba" },
    { "v0" : 10, "v1" : 11, "trait" : "kickOffBarrier" },
    
    { "v0" : 12, "v1" : 13, "color" : "e9cc6e", "x" : -8727, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 14, "v1" : 15, "color" : "e9cc6e", "x" : 872, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 16, "v1" : 17, "color" : "e9cc6e", "x" : -1745, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    
    { "v0" : 18, "v1" : 19, "color" : "e9cc6e", "x" : -872, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "trait" : "ballArea", "cMask" : ["wall" ] },
    
    { "v0" : 20, "v1" : 21, "color" : "e9cc6e", "x" : -4363, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 22, "v1" : 23, "color" : "e9cc6e", "x" : -1200, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 24, "v1" : 25, "color" : "e9cc6e", "x" : -6109, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 26, "v1" : 27, "color" : "e9cc6e", "x" : -6981, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 28, "v1" : 29, "color" : "e9cc6e", "x" : -7854, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 30, "v1" : 31, "color" : "e9cc6e", "x" : -8727, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 32, "v1" : 33, "color" : "e9cc6e", "x" : -3490, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 34, "v1" : 35, "color" : "e9cc6e", "x" : -2618, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 36, "v1" : 37, "color" : "e9cc6e", "x" : 1745, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 38, "v1" : 39, "color" : "e9cc6e", "x" : 2618, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 40, "v1" : 41, "color" : "e9cc6e", "x" : 3490, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 42, "v1" : 43, "color" : "e9cc6e", "x" : 4363, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 44, "v1" : 45, "color" : "e9cc6e", "x" : 5236, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 46, "v1" : 47, "color" : "e9cc6e", "x" : 6109, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 48, "v1" : 49, "color" : "e9cc6e", "x" : 1600, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 50, "v1" : 51, "color" : "e9cc6e", "x" : 7854, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 52, "v1" : 53, "color" : "e9cc6e", "x" : 8727, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 54, "v1" : 55, "color" : "e9cc6e", "x" : -7854, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 56, "v1" : 57, "color" : "e9cc6e", "x" : -6981, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 58, "v1" : 59, "color" : "e9cc6e", "x" : -6109, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 60, "v1" : 61, "color" : "e9cc6e", "x" : -1200, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 62, "v1" : 63, "color" : "e9cc6e", "x" : -4363, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 64, "v1" : 65, "color" : "e9cc6e", "x" : -800, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 66, "v1" : 67, "color" : "e9cc6e", "x" : -2618, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 68, "v1" : 69, "color" : "e9cc6e", "x" : -1745, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 70, "v1" : 71, "color" : "e9cc6e", "x" : -872, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 72, "v1" : 73, "color" : "e9cc6e", "x" : 872, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 74, "v1" : 75, "color" : "e9cc6e", "x" : 1745, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 76, "v1" : 77, "color" : "e9cc6e", "x" : 2618, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 78, "v1" : 79, "color" : "e9cc6e", "x" : 3490, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 80, "v1" : 81, "color" : "e9cc6e", "x" : 1000, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 82, "v1" : 83, "color" : "e9cc6e", "x" : 5236, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 84, "v1" : 85, "color" : "e9cc6e", "x" : 6109, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 86, "v1" : 87, "color" : "e9cc6e", "x" : 1600, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 88, "v1" : 89, "color" : "e9cc6e", "x" : 7854, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    { "v0" : 90, "v1" : 91, "color" : "e9cc6e", "x" : 8727, "cGroup" : ["red","blue" ], "bCoef" : 0, "curve" : 0, "vis" : true, "cMask" : ["wall" ] },
    
    { "curve" : 0, "vis" : true, "color" : "e9cc6e", "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 92, "v1" : 93 },
    { "curve" : 0, "vis" : true, "color" : "e9cc6e", "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 93, "v1" : 94 },
    
    { "color" : "e9cc6e", "cMask" : ["ball" ], "v0" : 95, "v1" : 96, "curve" : 155.898430233, "cGroup" : ["ball","red","blue" ] },
    { "color" : "e9cc6e", "cMask" : ["ball" ], "v0" : 96, "v1" : 97, "curve" : 28.7683142519, "cGroup" : ["ball","red","blue" ] },
    { "color" : "e9cc6e", "cMask" : ["ball" ], "v0" : 97, "v1" : 98, "cGroup" : ["ball","red","blue" ] },
    
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 99, "v1" : 100 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 100, "v1" : 101 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 101, "v1" : 102, "curve" : 225.501952686 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 103, "v1" : 104 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 104, "v1" : 105 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0.1, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 106, "v1" : 107 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 108, "v1" : 109 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 109, "v1" : 110 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 111, "v1" : 112 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 113, "v1" : 114, "curve" : 263.267078673 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 115, "v1" : 116, "x" : -220 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 116, "v1" : 117, "x" : -220 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 118, "v1" : 119, "x" : -220 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 119, "v1" : 120, "x" : -220 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 120, "v1" : 121, "curve" : 263.267078673, "x" : -220 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 122, "v1" : 123 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 123, "v1" : 124 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 125, "v1" : 126 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 127, "v1" : 128 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 128, "v1" : 129 },
    { "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 129, "v1" : 130, "curve" : 225.501952686 },
    
    { "color" : "e9cc6e", "cMask" : ["ball" ], "v0" : 131, "v1" : 132, "curve" : 155.898430233, "cGroup" : ["ball","red","blue" ], "bCoef" : 0 },
    { "color" : "e9cc6e", "cMask" : ["ball" ], "v0" : 132, "v1" : 133, "curve" : 28.7683142519, "cGroup" : ["ball","red","blue" ], "bCoef" : 0 },
    { "color" : "e9cc6e", "cMask" : ["ball" ], "v0" : 133, "v1" : 134, "cGroup" : ["ball","red","blue" ], "bCoef" : 0 },
    
    { "curve" : 0, "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 135, "v1" : 136 },
    { "curve" : 0, "vis" : true, "color" : "e9cc6e", "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 136, "v1" : 137 },
    { "curve" : -180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 138, "v1" : 139, "color" : "e9cc6e" },
    { "curve" : 180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 138, "v1" : 139, "color" : "e9cc6e" },
    { "curve" : -180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 140, "v1" : 141, "color" : "e9cc6e" },
    { "curve" : 180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 140, "v1" : 141, "color" : "e9cc6e" },
    { "curve" : -180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 142, "v1" : 143, "color" : "e9cc6e" },
    { "curve" : 180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 142, "v1" : 143, "color" : "e9cc6e" },
    { "curve" : -180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 144, "v1" : 145, "color" : "e9cc6e" },
    { "curve" : 180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 144, "v1" : 145, "color" : "e9cc6e" },
    { "curve" : -180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 146, "v1" : 147, "color" : "e9cc6e" },
    { "curve" : 180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 146, "v1" : 147, "color" : "e9cc6e" },
    { "curve" : -180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 148, "v1" : 149, "color" : "e9cc6e" },
    { "curve" : 180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 148, "v1" : 149, "color" : "e9cc6e" },
    { "curve" : -180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 150, "v1" : 151, "color" : "e9cc6e" },
    { "curve" : 180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 150, "v1" : 151, "color" : "e9cc6e" },
    { "curve" : -180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 152, "v1" : 153, "color" : "e9cc6e" },
    { "curve" : 180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 152, "v1" : 153, "color" : "e9cc6e" },
    { "curve" : -180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 154, "v1" : 155, "color" : "e9cc6e" },
    { "curve" : 180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 154, "v1" : 155, "color" : "e9cc6e" },
    { "curve" : -180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 156, "v1" : 157, "color" : "e9cc6e" },
    { "curve" : 180, "vis" : true, "bCoef" : 0, "cMask" : ["ball" ], "cGroup" : ["ball","red","blue" ], "trait" : "ballArea", "v0" : 156, "v1" : 157, "color" : "e9cc6e" },
    { "curve" : 0, "vis" : true, "color" : "e9cc6e", "bCoef" : 1, "cMask" : ["wall" ], "trait" : "ballArea", "v0" : 1, "v1" : 5, "y" : 192 },
    { "curve" : 0, "vis" : true, "color" : "e9cc6e", "bCoef" : 1, "cMask" : ["wall" ], "trait" : "ballArea", "v0" : 2, "v1" : 6, "y" : -192 },
    
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "b34e4e", "curve" : 0, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "b34e4e", "curve" : 2.5, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "b34e4e", "curve" : 5, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "b34e4e", "curve" : 7.5, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "b34e4e", "curve" : 10, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "aa4d4d", "curve" : 13, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "a34b4b", "curve" : 15, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "9a4949", "curve" : 17, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "934b4b", "curve" : 16, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "8a4d4d", "curve" : 23, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "834f4f", "curve" : 18, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "7a5151", "curve" : 19, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "735353", "curve" : 20, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "6a5555", "curve" : 21, "cMask" : ["wall" ] },
    { "v0" : 1, "v1" : 2, "trait" : "coverup", "color" : "635757", "curve" : 22, "cMask" : ["wall" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "5e5eba", "curve" : 0, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "5e5eba", "curve" : 2.5, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "5e5eba", "curve" : 5, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "5e5eba", "curve" : 7.5, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "5e5eba", "curve" : 10, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "5d5db6", "curve" : 13, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "5c5caa", "curve" : 14, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "5b5ba6", "curve" : 15, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "5a5a9a", "curve" : 16, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "5a5a8a", "curve" : 17, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "595986", "curve" : 18, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "59597a", "curve" : 19, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "585876", "curve" : 20, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "58586a", "curve" : 21, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] },
    { "v0" : 6, "v1" : 5, "trait" : "coverup", "color" : "575763", "curve" : 22, "cMask" : ["wall" ], "cGroup" : ["red","blue" ] }

  ],

  "goals" : [
    { "p0" : [-9492,181 ], "p1" : [-9492,-179 ], "team" : "red" },
    { "p0" : [9500,182 ], "p1" : [9500,-178 ], "team" : "blue" }

  ],

  "discs" : [
    { "pos" : [-867,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-1740,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-2618,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [1,272 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-3484,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-4358,269 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-5236,269 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-6105,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-6978,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-7853,269 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-8722,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [8730,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [7857,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [6979,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [6113,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [5239,269 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [4361,269 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [3492,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [2619,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [1744,269 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [875,270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-871,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-1744,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-2622,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [0,-273 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-3488,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-4362,-271 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-5240,-271 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-6109,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-6982,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-7857,-271 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [-8726,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [8726,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [7853,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [6975,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [6109,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [5235,-271 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [4357,-271 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [3488,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [2615,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [1740,-271 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 },
    { "pos" : [871,-270 ], "radius" : 7, "cMask" : ["red","blue" ], "cGroup" : ["ball" ], "trait" : "ballArea", "bCoef" : 0.2, "curve" : -180, "color" : "000000", "invMass" : 0 }

  ],

  "planes" : [
    { "normal" : [0,1 ], "dist" : -192, "trait" : "ballArea" },
    { "normal" : [0,-1 ], "dist" : -192, "trait" : "ballArea" },
    
    { "normal" : [0,1 ], "dist" : -280, "bCoef" : 0.1 },
    { "normal" : [0,-1 ], "dist" : -280, "bCoef" : 0.1 },
    { "normal" : [1,0 ], "dist" : -9596, "bCoef" : 0.1 },
    { "normal" : [-1,0 ], "dist" : -9596, "bCoef" : 0.1 }

  ],

  "traits" : {
    "cornerflag" : { "radius" : 3, "invMass" : 0, "bCoef" : 0.5, "color" : "FFFF00", "cGroup" : ["" ] },
    "ballArea" : { "vis" : false, "bCoef" : 1, "cMask" : ["ball" ] },
    "goalPost" : { "radius" : 8, "invMass" : 0, "bCoef" : 0.5 },
    "goalNet" : { "vis" : true, "bCoef" : 0.1, "cMask" : ["ball" ] },
    "kickOffBarrier" : { "vis" : false, "bCoef" : 0.1, "cGroup" : ["redKO","blueKO" ], "cMask" : ["red","blue" ] }

  },

  "playerPhysics" : {
    "bCoef" : 1.5,
    "invMass" : 0.5,
    "damping" : 0.9995,
    "acceleration" : 0.0249,
    "kickingAcceleration" : 0.0175,
    "kickingDamping" : 0.9995,
    "kickStrength" : 5.6

  },

  "ballPhysics" : {
    "radius" : 10,
    "bCoef" : 0.5,
    "invMass" : 1,
    "damping" : 0.99,
    "color" : "e9cc6e",
    "cMask" : [ "all"
    ],
    "cGroup" : [ "ball"
    ]

  }
}
`

export { longbounce3v3 }