# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    url: <%= ENV["BLAZER_DATABASE_URL"] %>

    # statement timeout, in seconds
    # none by default
    # timeout: 15

    # caching settings
    # can greatly improve speed
    # off by default
    # cache:
    #   mode: slow # or all
    #   expires_in: 60 # min
    #   slow_threshold: 15 # sec, only used in slow mode

    # wrap queries in a transaction for safety
    # not necessary if you use a read-only user
    # true by default
    # use_transaction: false

    smart_variables:
      player_id: "SELECT id, name FROM players ORDER BY name ASC"
      other_player_id: "SELECT id, name FROM players ORDER BY name ASC"
      team_id: {0: "Spectator", 1: "Red", 2: "Blue"}
      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"
      # period: ["day", "week", "month"]
      # status: {0: "Active", 1: "Archived"}

    linked_columns:
      match_id: "/matches/{value}"
      player_id: "/players/{value}"
      other_player_id: "/players/{value}"
      # user_id: "/admin/users/{value}"

    smart_columns:
      player_id: "SELECT id, name FROM players WHERE id IN {value}"
      other_player_id: "SELECT id, name FROM players WHERE id IN {value}"
      team_id: {0: "Spectator", 1: "Red", 2: "Blue"}
      winner_team_id: {0: "Spectator", 1: "Red", 2: "Blue"}
      # user_id: "SELECT id, name FROM users WHERE id IN {value}"

# create audits
audit: true

# change the time zone
time_zone: "America/Argentina/Buenos_Aires"

# class name of the user model
user_class: Player

# method name for the current user
user_method: current_player

# method name for the display name
user_name: name

# custom before_action to use for auth
# before_action_method: require_admin

# email to send checks from
# from_email: blazer@example.org

# webhook for Slack
# slack_webhook_url: <%= ENV["BLAZER_SLACK_WEBHOOK_URL"] %>

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"

# enable anomaly detection
# note: with trend, time series are sent to https://trendapi.org
# anomaly_checks: prophet / trend / anomaly_detection

# enable forecasting
# note: with trend, time series are sent to https://trendapi.org
# forecasting: prophet / trend

# enable map
# mapbox_access_token: <%= ENV["MAPBOX_ACCESS_TOKEN"] %>

# enable uploads
# uploads:
#   url: <%= ENV["BLAZER_UPLOADS_URL"] %>
#   schema: uploads
#   data_source: main
